appname = "blog"
usage = "xiechuan blog"
version = "0.0.1"
author = "xiechuan"
email = "xiechuanj@gmail.com"

# include runtime.conf
runmode = "dev"

listenmode = "http"
projectaddr = "127.0.0.1:10000"
httpscertfile = "cert/blog/blog.crt"
httpskeyfile = "cert/blog/blog.key"

[log]
filepath = "log/backend.log"
level = "info"

[database]
driver = "mysql"
uri = "root:123456@tcp(127.0.0.1:3306)/blog?charset=utf8&parseTime=True&loc=Asia%2FShanghai"